# Generated by Django 4.1.4 on 2023-01-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default='2023-03-03 12:12:12'),
            preserve_default=False,
        ),
    ]
